import { TradeType } from '@tendieswap/sdk-core'
import { ChainId } from '@tendieswap/uniswap-smart-order-router'

import { CacheMode } from '@tendieswap/uniswap-smart-order-router'
import { CachedRoutesStrategy } from './model/cached-routes-strategy'
import { PairTradeTypeChainId } from './model/pair-trade-type-chain-id'
import { CachedRoutesBucket } from './model/cached-routes-bucket'

/**
 * This is the main configuration for the caching strategies of routes.
 *
 * The keys are generated by calling the `toString` method in the `PairTradeTypeChainId` class,
 * this way we can guarantee the correct format of the key.
 *
 * The values are an object of type `CachedRoutesStrategy`.
 * which receive an array of `CachedRoutesParameters` with the configuration of the buckets.
 */
export const CACHED_ROUTES_CONFIGURATION: Map<string, CachedRoutesStrategy> = new Map([
  /**
   * WTENET/USDC - TENET
   */
  [
    new PairTradeTypeChainId({
      tokenIn: '0xd6cb8a253e12893b0cF39Ca78F7d858652cCa1fe', // WTENET
      tokenOut: '0x55c32e8aB56021C012AB3d5a586b743664E73DA0', // USDC
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'WTENET/USDC',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
      buckets: [
        new CachedRoutesBucket({ bucket: 0.2, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 1, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 3, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 5, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 8, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 13, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 21, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 34, cacheMode: CacheMode.Livemode }),
        new CachedRoutesBucket({ bucket: 55, cacheMode: CacheMode.Livemode }),
      ],
    }),
  ],
  [
    new PairTradeTypeChainId({
      tokenIn: '0xd6cb8a253e12893b0cF39Ca78F7d858652cCa1fe', // WTENET
      tokenOut: '*', // ANY TOKEN
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'WTENET/*',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
      buckets: [
        new CachedRoutesBucket({ bucket: 100, cacheMode: CacheMode.Darkmode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 300, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 500, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 750, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 1_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 3_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 8_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 13_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
      ],
    }),
  ],
  [
    new PairTradeTypeChainId({
      tokenIn: '0x55c32e8aB56021C012AB3d5a586b743664E73DA0', // USDC
      tokenOut: '*', // ANY TOKEN
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
    }).toString(),
    new CachedRoutesStrategy({
      pair: 'USDC/*',
      tradeType: TradeType.EXACT_INPUT,
      chainId: ChainId.TENET,
      buckets: [
        new CachedRoutesBucket({ bucket: 100, cacheMode: CacheMode.Darkmode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 300, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 500, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 750, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 1_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 3_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 8_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
        new CachedRoutesBucket({ bucket: 13_000, cacheMode: CacheMode.Livemode, withLastNCachedRoutes: 10 }),
      ],
    }),
  ],
  /**
   * NOTE: Only Cache configuration for Pricing below this comment
   * These configurations are influenced by the frontend configuration:
   * https://github.com/Uniswap/interface/blob/main/src/hooks/useUSDPrice.ts#L15
   */

])
